name: pro_design_6
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bubble_bottom_bar: ^1.2.0
  font_awesome_flutter: ^8.5.0
  material_design_icons_flutter: ^3.2.3895
  badges: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.otf
        - asset: fonts/Gilroy-ExtraBold.otf
          weight: 700
